### ISSUE TITLE
"Get challenge" not working?

### ISSUE THREAD

**Issue by 2600box** [divadvo/UBS2YNAB#2]
Hello, I am trying this for the first time and add my contact number and spin up the docker. 

When I click get challenge it just spins... It is meant to open a pop-up for something?

Log in docker are not very informative...

```
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:27:18 +0000] "GET / HTTP/1.1" 200 2255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:27:18 +0000] "GET /static/js/main.0160f94c.chunk.js HTTP/1.1" 200 3707 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:27:18 +0000] "GET /static/css/main.9c96dd7f.chunk.css HTTP/1.1" 200 520247 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:27:18 +0000] "GET /static/js/2.d0bd9500.chunk.js HTTP/1.1" 200 650855 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac
OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:27:18 +0000] "GET /favicon.ico HTTP/1.1" 200 3150 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:30:58 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:00 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET / HTTP/1.1" 200 2255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET /manifest.json HTTP/1.1" 200 492 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET /static/js/main.0160f94c.chunk.js HTTP/1.1" 200 3707 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET /static/js/2.d0bd9500.chunk.js HTTP/1.1" 200 650855 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac
OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET /static/css/main.9c96dd7f.chunk.css HTTP/1.1" 200 520247 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:31:15 +0000] "GET /favicon.ico HTTP/1.1" 200 3150 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:10 +0000] "GET / HTTP/1.1" 200 2255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:10 +0000] "GET /static/js/main.0160f94c.chunk.js HTTP/1.1" 200 3707 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:10 +0000] "GET /static/css/main.9c96dd7f.chunk.css HTTP/1.1" 200 520247 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:10 +0000] "GET /static/js/2.d0bd9500.chunk.js HTTP/1.1" 200 650855 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac
OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:11 +0000] "GET /logo192.png HTTP/1.1" 200 5347 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
ubs2ynab-react-frontend  | 10.0.0.18 - - [24/Aug/2022:16:41:11 +0000] "GET /favicon.ico HTTP/1.1" 200 3150 "http://10.0.0.50:5002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
```

**Comment by 2600box** [comment]
I figured it out, `API_URL=http://localhost:5001` means that the shared config needs to be on the same machine as the browser...

**Comment by 2600box** [comment]
Still have not been able to download any statements. After it authenticates, and I select a date, it just spins and spins and there is no more update in the console

**Comment by 2600box** [comment]
I have not tried to install docker on my local machine yet... but this what I can see in the logs... I did also try port forwarding 5001 and 5002 and connecting to localhost with the same result, then I tried change the API_URL config and same thing...
```
ub2ynab-go-api           | {"time":"2022-08-24T18:10:29.93289645Z","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] unexpected end of JSON input goroutine 19 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1()\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:77 +0x10d\npanic({0x808a00, 0xc00029e708})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/divadvo/UBS2YNAB/go-api/ubsApi.SendAuthenticatorChallengeResponse({0xc000290800, 0x2}, {0xc000290803, 0x2}, {0xc000290806, 0x2}, {0xc000290809, 0x2})\n\t/build/ubsApi/api.go:142 +0xd34\nmain.processChallengeResponse({0x93c690, 0xc0001f8b40})\n\t/build/main.go:55 +0x145\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x93c690, 0xc0001f8b40})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:522 +0x51\ngithub.com/labstack/echo/v4/middleware.StaticWithConfig.func1.1({0x93c690, 0xc0001f8b40})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/static.go:169 +0x219\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x93c690, 0xc0001f8b40})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/cors.go:121 +0x57c\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1({0x93c690, 0xc0001f8b40})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:98 +0xf8\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x93c690, 0xc0001f8b40})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/logger.go:117 +0xe2\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00012c000, {0x938208?, 0xc000212000}, 0xc000078500)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:633 +0x3d1\nnet/http.serverHandler.ServeHTTP({0x937028?}, {0x938208, 0xc000212000}, 0xc000078500)\n\t/usr/local/go/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc0000b1680, {0x9386c0, 0xc000134870})\n\t/usr/local/go/src/net/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3102 +0x4db\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f8b54d56fd8, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:305 +0x89\ninternal/poll.(*pollDesc).wait(0xc000114480?, 0x203000?, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0xc000114480)\n\t/usr/local/go/src/internal/poll/fd_unix.go:614 +0x234\nnet.(*netFD).accept(0xc000114480)\n\t/usr/local/go/src/net/fd_unix.go:172 +0x35\nnet.(*TCPListener).accept(0xc0000ae5d0)\n\t/usr/local/go/src/net/tcpsock_posix.go:142 +0x28\nnet.(*TCPListener).AcceptTCP(0xc0000ae5d0)\n\t/usr/local/go/src/net/tcpsock.go:275 +0x3d\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x4409a0?})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:875 +0x1d\nnet/http.(*Server).Serve(0xc00012a000, {0x937ed8, 0xc0000b20a8})\n\t/usr/local/go/src/net/http/server.go:3070 +0x385\ngithub.com/labstack/echo/v4.(*Echo).StartServer(0xc00012c000, 0xc00012a000)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:724 +0x532\ngithub.com/labstack/echo/v4.(*Echo).Start(...)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:644\nmain.main()\n\t/build/main.go:38 +0x685\n\ngoroutine 49 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f8b54d56df8, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:305 +0x89\ninternal/poll.(*pollDesc).wait(0xc000114100?, 0xc0002fc000?, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Read(0xc000114100, {0xc0002fc000, 0x1000, 0x1000})\n\t/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a\nnet.(*netFD).Read(0xc000114100, {0xc0002fc000?, 0xc00020a6c0?, 0x6a4905?})\n\t/usr/local/go/src/net/fd_posix.go:55 +0x29\nnet.(*conn).Read(0xc0000b2140, {0xc0002fc000?, 0x64684e57616d6c47?, 0x6442426962766c47?})\n\t/usr/local/go/src/net/net.go:183 +0x45\nnet/http.(*connReader).Read(0xc0002806c0, {0xc0002fc000, 0x1000, 0x1000})\n\t/usr/local/go/src/net/http/server.go:786 +0x171\nbufio.(*Reader).fill(0xc000294120)\n\t/usr/local/go/src/bufio/bufio.go:106 +0xff\nbufio.(*Reader).ReadSlice(0xc000294120, 0x0?)\n\t/usr/local/go/src/bufio/bufio.go:372 +\n"}
ub2ynab-go-api           | {"time":"2022-08-24T18:10:29.932982785Z","id":"","remote_ip":"192.168.224.1","host":"localhost:5001","method":"POST","uri":"/challenge-response","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0","status":500,"error":"","latency":447429444,"latency_human":"447.429444ms","bytes_in":55,"bytes_out":36}
```

**Comment by divadvo** [comment]
Hi @2600box, my project and the underlying implementation https://github.com/Che4ter/UBStoYNAB have not been working for me for multiple months now. 

Please try the project by Che4ter and see if it works, I assume it won't 

I didn't implement the actual calls to UBS APIs. Che4ter did. 
Please also see this issue: https://github.com/Che4ter/UBStoYNAB/issues/2
I assume these APIs have been blocked or changed by UBS, so there isn't much I can do about it.



Recently I've been manually exporting csv's from UBS and converting them using https://github.com/bank2ynab/bank2ynab
